#!/usr/bin/env python

import os, sys
import subprocess
import fnmatch

# FUNCTIONS

def getReferenceOutput(cacheFile):
    system_command = "wacc_examples/refCompile -a -d wacc_examples/valid"
    process = subprocess.Popen(system_command.split(), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    output = process.communicate()[0].split('\n')
    if len(output) == 1 and len(output[0]) == 0:
        print "Couldn't get reference output. Either:"
        print "\t1: Thank Mark for using a silly system ruby instead of a local one."
        print "\t2: You're not on campus."
        exit(1)
    makeFileDirectory(cacheFile)
    with open(cacheFile, 'w') as f:
        f.write('\n'.join(output))
    return output


def cacheOutput():
    cacheFile = 'test_compile_output/cachedData.txt'
    if (os.path.exists(cacheFile)):
        with open(cacheFile, 'r') as f:
            data = f.read().split('\n')
            if (len(data) < 10):
                data = getReferenceOutput(cacheFile)
    else:
        data = getReferenceOutput(cacheFile)
    return data


def compile(filename):
    system_command = "./compile {0}".format(filename)
    process = subprocess.Popen(system_command.split(), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    output = process.communicate()[0]
    newfile = 'test_compile_output/compiled_output' + filename.split('wacc_examples')[1]
    newfile = newfile.replace('.wacc', '.s')
    makeFileDirectory(newfile)
    with open(newfile, 'w') as f:
        f.write(output)


def makeFileDirectory(file_path):
    file_dirs = file_path.split('/')
    i = 0
    while (i < len(file_dirs) - 1):
        current_dir = "/".join(file_dirs[:i + 1])
        if not os.path.exists(current_dir):
            os.mkdir(current_dir)
        i += 1


def getDataFromOutput(output):
    data = []
    i = 0
    while (i < len(output)):
        if "calling the reference compiler on" in output[i]:
            filename = output[i][34:]  # Gets the text after the above

            # Get expected output
            while 'Output:' not in output[i-1]: i += 1
            output_exec = []
            while '# ' in output[i]:
                output_exec.append(output[i][2:])
                i += 1

            # Get expected assembly
            separator = '==========================================================='
            while (separator not in output[i]):
                i += 1
            assembly = []
            i += 1
            while (separator not in output[i]):
                assembly.append('\t'.join(output[i].split('\t')[1:]))
                i += 1
            data.append((filename.replace('wacc', 's'), '\n'.join(assembly), '\n'.join(output_exec)))
        i += 1
    return data


def writeData(data):
    for i in data:
        data_path = "test_compile_output/{0}".format(i[0])
        makeFileDirectory(data_path)
        with open(data_path, 'w') as f:
            f.write(i[1])


def compareFiles(file_1, file_2):
    with open(file_1, 'r') as f1:
        with open(file_2, 'r') as f2:
            return f1.read() == f2.read()

def runFile(file_in, file_out):
    system_command = "arm-linux-gnueabi-gcc -o {1} -mcpu=arm1176jzf-s -mtune=arm1176jzf-s {0}".format(file_in, file_out)
    process = subprocess.Popen(system_command.split(), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    print process.communicate()
    system_command = "qemu-arm -L /usr/arm-linux-gnueabi/ {0}".format(file_out)
    process = subprocess.Popen(system_command.split(), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    output = process.communicate()[0]
    os.remove(file_out)
    with open(file_out, 'w') as f:
        f.write(output)
    return file_out

def show_error(file_1_orig, file1, file2):
    print '====================================='
    print '{0} has a compile error:\n'.format(file_1_orig.split('/')[-1])
    system_command = "diff {0} {1}".format(file1, file2)
    process = subprocess.Popen(system_command.split(), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    print process.communicate()[0]

def show_output_error(file_1_orig, file1, file2):
    print '====================================='
    print '{0} has an output error:\n'.format(file_1_orig.split('/')[-1])
    outputfile1 = 'output1.txt'
    outputfile2 = 'output2.txt'
    system_command = "diff {0} {1}".format(runFile(file1, outputfile1), runFile(file2, outputfile2))
    os.remove(outputfile1)
    os.remove(outputfile2)
    process = subprocess.Popen(system_command.split(), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    print process.communicate()[0]

def validateOutput(file1, file2):
    system_command = "which arm-linux-gnueabi-gcc"
    process = subprocess.Popen(system_command.split(), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if 'not found' in process.communicate()[0]:
        raise IOError
    system_command = "which qemu-arm"
    process = subprocess.Popen(system_command.split(), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if 'not found' in process.communicate()[0] or not os.path.exists('/usr/arm-linux-gnueabi'):
        raise IOError
    output1 = 'output1.txt'
    output2 = 'output2.txt'
    runFile(file1, output1)
    runFile(file2, output2)
    with open(output1, 'r') as f1:
        with open(output2, 'r') as f2:
            return f1.read() == f2.read()

def verify_file(root, filename):
    compile_file = os.path.join(root, filename)
    compile(compile_file)
    compile_file = compile_file.replace('wacc_examples', 'test_compile_output/compiled_output')
    compile_file = compile_file.replace('.wacc', '.s')
    referenceOutput = compile_file.replace('compiled_output', 's_examples')
    correct = True
    try:
        if not compareFiles(compile_file, referenceOutput):
            try:
                if not validateOutput(compile_file, referenceOutput):
                    show_output_error(filename, compile_file, referenceOutput)
            except IOError:
                show_error(filename, compile_file, referenceOutput)
                correct = False
    except IOError:
        correct = False
    return correct


def printResult(verified, incorrect):
    print '====================================='
    print '====================================='
    print 'Verified:\t{0}'.format(verified)
    print 'Correct:\t{0}'.format(verified - incorrect)
    print 'Incorrect:\t{0}'.format(incorrect)


# MAIN

output = cacheOutput()
data = getDataFromOutput(output)
writeData(data)

verified = 0
incorrect = 0

root = 'wacc_examples/valid'

if len(sys.argv) > 1:
    path = sys.argv[1]
    if '.wacc' in path:
        verified += 1
        if not verify_file('/'.join(path.split('/')[:-1]), path.split('/')[-1]):
            incorrect += 1
        printResult(verified, incorrect)
        exit(0)
    else:
        root = path

for root, dirnames, filenames in os.walk(root):
    for filename in fnmatch.filter(filenames, '*.wacc'):
        verified += 1
        if not verify_file(root, filename):
            incorrect += 1

printResult(verified, incorrect)
