#!/usr/bin/ruby
# Ruby front-end for your compiler.
ARGV.each do|a|
    system("java -cp bin:lib/antlr-4.4-complete.jar wacc.Main < #{a}")
    if ($?.exitstatus != 0)
      print "\nTried compiling #{a}\n\n"
      if ($?.exitstatus == 100)
        print "There was a syntax error...\n"
      end
      if ($?.exitstatus == 200)
        print "There was a semantic error...\n"
      end
      exit $?.exitstatus
    end
end
