#!/bin/bash

DIR="$(pwd -P)"

cd test
export TESTS=$(find * -type f -follow -print | sed 's/\//\./g' | sed 's/.java//g' | grep -v "find_tests" | awk -F ' ' '{ print $1 }')

cd "$DIR"

make test_compile
make $TESTS
