#!/bin/bash

DIR="$(pwd -P)"

cd test
export TESTS=$(find * -type f -follow -print | sed 's/\//\./g' | sed 's/.java//g' | grep -v "find_tests" | awk -F ' ' '{ print $1 }')

cd "$DIR"

make test_compile 1>/dev/null

STATUS=$?
if (( $STATUS != 0 )); then
  make clean 1>/dev/null
  echo -e "\nThere was an error in compilation. Tests will not run.Run `make test_compile` to see errors\n---------------------------------\n"
  exit $STATUS
fi

for i in $TESTS; do
  TEST_DATA=$(make $i)

  STATUS=$?
  if (( $STATUS != 0 )); then
    LINE_COUNT=$(echo "$TEST_DATA" | wc -l)
    LINE_COUNT=$((LINE_COUNT - 4))
    echo -e "\nThere was an error in testing $i.\n---------------------------------\n$(echo "$TEST_DATA" | tail -n $LINE_COUNT)\n---------------------------------"
  else
    echo -e "Test:\t$i passed"
  fi
done
